[dependencies]
anyhow = "1.0.79"
async-recursion = "1.0.5"
async-trait = "0.1.77"
chrono = "0.4.31"
clap = { features = ["cargo", "derive", "env"], version = "4.4.18" }
clap-markdown = "0.1.3"
clap-verbosity-flag = "2.1.2"
clap_complete = "4.4.8"
colored = "2.1.0"
directories = "5.0.1"
futures = "0.3.30"
indicatif = "0.17.7"
inquire = "0.6.2"
local-ip-address = "0.5.7"
mime_guess = "2.0.4"
reqwest = { features = ["json"], version = "0.11.23" }
serde = { features = ["derive"], version = "1.0.195" }
serde_json = "1.0.111"
tabled = { features = ["ansi"], version = "0.15.0" }
tokio = { features = ["full"], version = "1.35.1" }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
whoami = "1.4.1"

[package]
authors = ["liblaf <i@liblaf.me>"]
description = "CLIs written in Rust"
edition = "2021"
license = "MIT"
name = "claps"
readme = "README.md"
repository = "https://github.com/liblaf/claps"
version = "0.1.0"
