[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.74"
clap = { features = ["cargo", "derive", "env"], version = "4.4.11" }
clap-markdown = "0.1.3"
clap-verbosity-flag = "2.1.0"
clap_complete = "4.4.4"
colored = "2.0.4"
local-ip-address = "0.5.6"
reqwest = { features = ["json"], version = "0.11.22" }
serde = { features = ["derive"], version = "1.0.193" }
tabled = { features = ["color"], version = "0.14.0" }
tokio = { features = ["full"], version = "1.34.0" }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
whoami = "1.4.1"

[package]
authors = ["liblaf <i@liblaf.me>"]
edition = "2021"
license = "MIT"
name = "claps"
readme = "README.md"
repository = "https://github.com/liblaf/claps"
version = "0.0.0"
