words:
  - afinet
  - choco
  - ddns
  - folderid
  - gomod
  - indicatif
  - liblaf
  - netifas
  - nointeraction
  - swatinem
ignorePaths:
  - "*-lock.*"
  - "*.lock"
dictionaries:
  - bash
  - cpp
  - cpp-refined
  - dotnet
  - makefile
  - npm
  - rust
allowCompoundWords: true
