version: "3"

vars:
  HOST:
    sh: |
      rustc --version --verbose | sed --quiet "s/host: //p"
  TARGETS: bws ddns gfw pic

tasks:
  default:
    - cargo check
    - cargo clippy

  clean:
    cmds:
      - cargo clean
      - cmd: rm --force --recursive --verbose dist
        silent: true

  dist:
    cmds:
      - cargo build --bins --release
      - cmd: install -D --no-target-directory --verbose "target/release/{{.ITEM}}{{exeExt}}" "dist/{{.ITEM}}-{{.HOST}}{{exeExt}}"
        for:
          var: TARGETS
        silent: true

  docs:
    cmds:
      - cmd: mkdir --parents --verbose docs
      - cmd: |
          mkdir --parents --verbose "docs/{{.ITEM}}"
          cargo run --bin="{{.ITEM}}" complete man > "docs/{{.ITEM}}/{{.ITEM}}.1"
          pandoc --output="docs/{{.ITEM}}/README.md" "docs/{{.ITEM}}/{{.ITEM}}.1"
        for:
          var: TARGETS
      - prettier --write docs
