version: "3"

vars:
  HOST:
    sh: |
      rustc --version --verbose | sed --quiet "s/host: //p"
  TARGETS: ddns-cli

tasks:
  default:
    - cargo check
    - cargo clippy

  clean:
    cmds:
      - cargo clean
      - cmd: rm --force --recursive --verbose dist
        silent: true

  dist:
    cmds:
      - cargo build --release
      - cmd: install -D --no-target-directory --verbose "target/release/{{.ITEM}}{{exeExt}}" "dist/{{.ITEM}}-{{.HOST}}{{exeExt}}"
        for:
          var: TARGETS
        silent: true
