name: CI

on:
  push:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust Toolchain
        run: |
          rustup default stable
          rustup update stable
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ github.token }}
      - name: Install GNU Softwares
        uses: liblaf/template/.github/actions/install@main
        with:
          brew: coreutils gnu-sed
          choco: gnuwin32-coreutils.install sed
      - name: Build
        run: task dist
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ runner.arch }}
          path: dist/*
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

  upload:
    name: Upload Release Assets
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Delete Existing Release
        run: gh release --repo="${{ github.repository }}" delete dev --cleanup-tag
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true
      - name: Upload Release Assets
        run: gh release --repo="${{ github.repository }}" create dev artifacts/**/* --generate-notes --prerelease
        env:
          GH_TOKEN: ${{ github.token }}
