name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Create GitHub Release
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      created: ${{ steps.release.outputs.releases_created }}
      tag: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        name: Create GitHub Release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: rust

  build:
    name: Build
    needs:
      - release
    if: needs.release.outputs.created == 'true'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Tools
        uses: liblaf/template/.github/actions/install@main
        with:
          brew: coreutils gnu-sed
          choco: gnuwin32-coreutils.install sed
          other: task
      - name: Install Rust Toolchain
        run: |
          rustup default ${{ matrix.toolchain }}
          rustup update ${{ matrix.toolchain }}
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: task dist
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ runner.arch }}-${{ matrix.toolchain }}
          path: dist/*
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        toolchain:
          - stable

  build-python:
    name: Build Python Package
    needs:
      - release
    if: needs.release.outputs.created == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Tools
        uses: liblaf/template/.github/actions/install@main
        with:
          other: poetry task
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install Dependencies
        run: poetry install
      - name: Build Package
        run: poetry run task python:build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: py${{ matrix.python-version }}
          path: dist/*
    strategy:
      matrix:
        python-version:
          - 3.11

  publish:
    name: Publish
    needs:
      - release
    if: needs.release.outputs.created == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust Toolchain
        run: rustup default stable
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  upload:
    name: Upload Release Assets
    permissions:
      contents: write
    needs:
      - build
      - release
    if: needs.release.outputs.created == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Upload Release Assets
        run: gh release --repo="${{ github.repository }}" upload "${{ needs.release.outputs.tag }}" * --clobber
        env:
          GH_TOKEN: ${{ github.token }}
